### ISSUE TITLE
After the zip is installed, no icon shows up.

### ISSUE THREAD

**Issue by samuelisme** [scristalli/SQL-Developer-4-keepalive#6] opened 2014-12-10 04:17 UTC
After I installed the zip file, no icon shows up. This happened after I installed it successfully, uninstalled it and try to install it again.

**Comment by burglar** [comment] 2015-01-09 17:37
It happened to me too. But for me, when I removed the jar file from the extensions folder, the extension did not get fully uninstalled, I still had the icon. So I went in Tools > Features and selected the "Installed Updates" tab. Then I just selected keepalive and press the uninstall button.
After restart the icon disapeared.
Then I went to install again and the icon stopped apearing. It looks like it did not install properly.

**Comment by kilx** [comment] 2015-01-14 12:09
I had this happen to me as well on Windows 7. However I solved the problem by starting SQL Developer with right click and "Run as administrator" and then installing the extension again. Didn't bother uninstalling after the first failed attempt.

Anyhow with the run as admin the icon appeared, not next to the save all button though but at the very end of the toolbar.

**Comment by scristalli** [comment] 2015-01-15 18:43
It seems to me that these problems are not entirely my extension's fault, but also due to a bad handling from SQL Developer of plugin installing/uninstalling. Do you agree?
Of course there might be some errors in the extension package, but I think that good software should refuse to install a broken plugin instead of breaking.
I think klix suggestion to run SQL Developer with privileges is good if it makes things work, but I don't know why (could it be related to the fact of necessary privileges under Linux? See the Installation Guide in the wiki).

Please comments with your thoughts, right now I don't see any effective way to tackle the problem as I think part of the responsibility is on SQL Developer.

**Comment by burglar** [comment] 2015-01-16 09:42
I agree with you, I think  most of the problem here is the way SQL Developer handles extensions.
Running SQL Developer with privileges doesn't work for me, so there might be other causes underlying.
I'll keep trying to find another way to work around it and if I find something I'll report back.

**Comment by Gene333** [comment] 2015-03-11 14:18
I'm running windows 7 64 bit, and SQL Developer 4.0.3, and am having the same issue. I've tried the 'run as admin' trick too but nothing will get the icon to show up

**Comment by scristalli** [comment] 2015-09-15 12:16
@Gene333 and anyone else still having problems: I'm going to close this issue as I think it's now clear that this type of problem has nothing to do with the extension development, but rather with external variables like file permissions, and most users succeeded in resolving the problems (cf. issue #12).

Please make sure that you run SQL Developer with elevated privileges, and only then (re)install the extension. You can also try changing the permissions on SQL Developer's directories, [as I suggested to do on Linux](https://github.com/scristalli/SQL-Developer-4-keepalive/wiki/English-guide).

If you do not succeed, feel free to open a new issue; in that case, please *clearly* state the problem, all the useful information you can provide about your environment, and the exact steps you have already tried to solve the issue. Thank you.

**Closed by scristalli** 2015-09-15 12:16 UTC
Labels: bug

**Comment by scristalli** [comment] 2015-09-15 12:17
Closing as related to issue #12, the same resolution applies.

**Comment by seliver** [comment] 2015-09-21 11:02
I can confirm that this is a problem caused by permission. Solved by installing sqldeveloper in my home folder.
