### ISSUE TITLE
Keepalive does not work on sqldeveloper-4.0.3.16.84

### ISSUE THREAD

**Issue by bricomatica** [scristalli/SQL-Developer-4-keepalive#9] opened 2015-02-05 08:54 UTC
After installing both 1.00 and 1.02 version of keepalive in the latest version of sqldeveloper (sqldeveloper-4.0.3.16.84) I can see the icon but when I click on that I get the following message:

Error during handleEvent on action 'keepalive' (id=351).
None of the attached controllers handled the action.
 - oracle.ide.controller.IdeAction$ControllerDelegatingController@1ad9584d[oracle.ideimpl.controller.ControllersHook$RuleBasedController@1ad9584d[keepalive.KeepaliveController][always-enabled]].

Best regards from Spain :)

**Comment by scristalli** [comment] 2015-09-15 12:36
This is very strange, since the controller will always return true in handleEvent(). I have no ideas, and no ways to reproduce the bug. To work on it, I'm afraid more information is needed. Anyone else having this issue?

**Comment by seliver** [comment] 2015-09-16 09:10
In my case, the extension will not appear at all.
Steps to reproduce:
- I installed from update, but selected no to restart as I had to save some scripts
- tried exiting the sqldeveloper through alt+f4 but it failed, so had to kill the process
- on starting, the icon did not appear
- tried installing again, but now selected to restart
- after restarting, the icon kept not appearing.

What do you think happened here?

**Comment by scristalli** [comment] 2015-09-16 11:02
@seliver, did you try running SQL Developer as administrator as suggested in some closed issues?
If not, please try to re-run the program with privileges, re-install the extension and restart.

**Comment by seliver** [comment] 2015-09-16 16:58
Will try that and give feedback.

**Comment by seliver** [comment] 2015-09-21 10:48
I did opened sqldeveloper with sudo, installed and indeed it worked, but only when executed under sudo.

**Comment by scristalli** [comment] 2015-10-31 13:49
@seliver problem has been solved (duplicate of other issues related to permissions), while the issue pointed out by @bricomatica still has not been reproduce.
I'm going to close this for now.

**Closed by scristalli** 2015-10-31 13:49 UTC
Labels: bug, cannot reproduce
