### ISSUE TITLE
When opening a second SQL Developer session, the plugin is not available.

### ISSUE THREAD

**Issue by BobSt** [scristalli/SQL-Developer-4-keepalive#15] opened 2015-10-02 11:51 UTC

**Comment by scristalli** [comment] 2015-10-05 07:53
Do you mean a second instance of SQL Developer? I just opened two instances and both had the extension available. Please provide the necessary details to reproduce the problem.

**Comment by scristalli** [comment] 2015-10-29 13:24
Having received no feedback, I'm going to close this (cannot reproduce without additional detail).

**Closed by scristalli** 2015-10-29 13:24 UTC
Labels: bug, cannot reproduce
