### ISSUE TITLE
org.netbeans.InvalidException after installing the extension

### ISSUE THREAD

**Issue by idsphilipmears** [scristalli/SQL-Developer-4-keepalive#7] opened 2014-12-23 16:58 UTC
After installing keepalive.zip (v1.2) module, SQL Developer fails to start with the following error:

Warning - could not install some modules: oracle.peek 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\lib\peek.jar: Not found bundle:oracle.peek oracle.external.xmlparser 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.external.xmlparser.jar: Not found bundle:oracle.external.xmlparser oracle.icons 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.icons.jar: Not found bundle:oracle.icons oracle.ide.macros 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\jdev\extensions\oracle.ide.macros.jar: Not found bundle:oracle.ide.macros oracle.ide.navigator 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\extensions\oracle.ide.navigator.jar: Not found bundle:oracle.ide.navigator oracle.external.xdk 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.external.xdk.jar: Not found bundle:oracle.external.xdk oracle.ide_boot 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\lib\ide-boot.jar: Not found bundle:oracle.ide_boot oracle.ide.vfs 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\extensions\oracle.ide.vfs.jar: Not found bundle:oracle.ide.vfs oracle.java_annotations 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\lib\annotations.jar: Not found bundle:oracle.java_annotations oracle.javamodel_rt 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.javamodel-rt.jar: Not found bundle:oracle.javamodel_rt oracle.ide.persistence 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\extensions\oracle.ide.persistence.jar: Not found bundle:oracle.ide.persistence org.eclipse.equinox.common 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\equinox\org.eclipse.equinox.common_3.6.0.v20100503.jar: Not found bundle:org.eclipse.equinox.common oracle.javatools_jdk 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\jdev\lib\jdkver.jar: Not found bundle:oracle.javatools_jdk oracle.ideimpl.peek 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\extensions\oracle.ideimpl.peek.jar: Not found bundle:oracle.ideimpl.peek oracle.external.oracle_jrf_adminserver 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.external.oracle-jrf-adminserver.jar: Not found bundle:oracle.external.oracle_jrf_adminserver oracle.uic 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\lib\uic.jar: Not found bundle:oracle.uic oracle.javaxide 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\lib\javax-ide.jar: Not found bundle:oracle.javaxide oracle.ide_osgi 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\lib\oracle.ide.osgi.jar: Not found bundle:oracle.ide_osgi oracle.jewt_core 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\jlib\jewt4.jar: Not found bundle:oracle.jewt_core oracle.ide.ceditor 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\extensions\oracle.ide.ceditor.jar: Not found bundle:oracle.ide.ceditor oracle.javatools 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\lib\javatools.jar: Not found bundle:oracle.javatools oracle.ide.library 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\jdev\extensions\oracle.ide.library.jar: Not found bundle:oracle.ide.library oracle.ide.file 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\extensions\oracle.ide.file.jar: Not found bundle:oracle.ide.file oracle.ide 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\extensions\oracle.ide.jar: Not found bundle:oracle.ide oracle.ide.indexing - org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\extensions\oracle.ide.indexing.jar: Not found bundle:oracle.ide.indexing oracle.external.timing 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.external.timing.jar: Not found bundle:oracle.external.timing oracle.external.jdbc 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.external.jdbc.jar: Not found bundle:oracle.external.jdbc oracle.ide.searchbar 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\extensions\oracle.ide.searchbar.jar: Not found bundle:oracle.ide.searchbar oracle.javatools_jndi_local 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.javatools-jndi-local.jar: Not found bundle:oracle.javatools_jndi_local oracle.external.miglayout 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.external.miglayout.jar: Not found bundle:oracle.external.miglayout oracle.external.odl 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.external.odl.jar: Not found bundle:oracle.external.odl oracle.external.nlsrtl 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.external.nlsrtl.jar: Not found bundle:oracle.external.nlsrtl oracle.external.balishare 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.external.balishare.jar: Not found bundle:oracle.external.balishare oracle.idert 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\lib\idert.jar: Not found bundle:oracle.idert oracle.external.berkeleydb 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.external.berkeleydb.jar: Not found bundle:oracle.external.berkeleydb oracle.javatools_nodeps 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.javatools-nodeps.jar: Not found bundle:oracle.javatools_nodeps oracle.jgoodies_looks 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\jlib\jgoodies-looks.jar: Not found bundle:oracle.jgoodies_looks oracle.external.jxlayer 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.external.jxlayer.jar: Not found bundle:oracle.external.jxlayer oracle.external.xdb 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.external.xdb.jar: Not found bundle:oracle.external.xdb oracle.external.oracle_jrf_dms 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\external\oracle.external.oracle-jrf-dms.jar: Not found bundle:oracle.external.oracle_jrf_dms oracle.ide_print_api 
- org.netbeans.InvalidException: Netigso: C:\Tools\sqldeveloper-4.0.0.13.80-no-jre\ide\lib\ide-print-api.jar: Not found bundle:oracle.ide_print_api

Options are "Disable Modules and Continue" or "Exit" - when "disable" is selected, SQLd still fails to open.

Version of Extention - keepalive.zip v1.2 (downloaded 12/23/2014)
Version of SQL Developer - sqldeveloper-4.0.0.13.80-no-jre
Version of JDK - `prompt:>javac -version`
     javac 1.7.0_21
Version of JRE - `prompt:>java -version`
     java version "1.8.0_25"
     Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
     Java HotSpot(TM) Client VM (build 25.25-b02, mixed mode)

SQL Developer restored to working condition by deleting 'keepalive.jar' from the extensions subfolder.

**Comment by scristalli** [comment] 2015-01-15 18:34
Thanks for reporting. I have no idea why this happens, I'll try reproducing the bug and get back later.

**Comment by benve83** [comment] 2015-05-11 11:34
Same for me, I've installed Netbeans 8.0.2.

Let us as soon as possibile.

Kind regards

**Comment by scristalli** [comment] 2015-09-15 12:27
This issue makes me think that your installation of SQL Developer doesn't include some libraries that are needed by the extension, for example the oracle.ide bundle ([MANIFEST.MF](https://raw.githubusercontent.com/scristalli/SQL-Developer-4-keepalive/master/SQL%20Developer%204%20keepalive/src/META-INF/MANIFEST.MF)).

Is there a chance you could try with another version of SQL Developer?

In case I'm right, the solution is simple: abandon whatever lightweight version of SQL Developer you're using that doesn't include such needed files.
In case I'm wrong, please comment again after testing with another version.

Thanks.

**Comment by scristalli** [comment] 2015-10-05 08:04
I'm marking this as "not a bug" as it is clear to me that it is not dependent on the implementation. Since I have not received feedback I'm also going to close, please reopen with additional details if you have them.

**Closed by scristalli** 2015-10-05 08:04 UTC
Labels: not a bug, resolution in progress

**Comment by SreecharanChallagundla** [comment] 2021-07-15 20:45
this issue still exists... 👎

**Comment by scristalli** [comment] 2021-07-15 21:07
@SreecharanChallagundla thanks for exhuming.
If you face a problem feel free to open/reopen an issue, but please post new information that might help resolve it, otherwise it is really hard to do something about it (and what I said in my last comment in 2015 is still true). Thank you.
